repos:
-   repo: https://github.com/psf/black
    rev: stable  # Replace with the desired Black version
    hooks:
    -   id: black
        args: [ --line-length=120 ]  # Optional: customize line length
